### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by follesoe** [zeltner/rosbridge_client_dot_net#3]
Hi,

I'm wondering if this project is being actively developed? Do you accept pull requests?

I'm looking to port this library into a .NET Core Library that can be used from various .NET platforms, such as Xamarin. So I'm wondering if I should create a new project from scratch, and re-use some of the classes, or if I should do a fork and create a .NET Core branch.

Just checking what your plans for this library are before going ahead.

Best regards,
Jonas

**Comment by zeltner** [comment]
Hi Jonas,

Sorry for the late reply. This repository was created during my graduate program and was not actively maintained after. I am happy to hear that you found it useful. I no longer have an environment or up-to-date ROS/.NET knowledge to properly review PRs, add new features or fix bugs so please fork the repository if you would like to add new features or fix bugs.

To avoid future confusion, I will add a note to the readme and archive the repository.

Best regards,
Stefan
