### ISSUE TITLE
Does this library support parallel calls?

### ISSUE THREAD

**Issue by maartenklerk** [zeltner/rosbridge_client_dot_net#4]
I am trying to implement this library in a sample project. I have differents Tasks running in parallel using the same messagedispatcher to do their work. Is that correct or should I use different messagedispatchers for every Task/Thread ?

In otherwords, is it threadsafe?

**Comment by zeltner** [comment]
I only used this library for a few small projects and never tested if it is
thread safe.  I didn't use it since two years and unfortunately don't have
the time and the environment to work on it right now but feel free to fork
it and make adjustments if required.
