### ISSUE TITLE
this platform does not support websocket protocol

### ISSUE THREAD

**Issue by looklin** [zeltner/rosbridge_client_dot_net#5]
For win7, this platform does not support websocket protocol. Is there a solution for this package?

**Comment by zeltner** [comment]
Sorry for the late reply. This repository was created during my graduate program and was not actively maintained after.  I no longer have an environment or up-to-date ROS/.NET knowledge to properly review PRs, add new features or fix bugs so please fork the repository if you would like to add new features or fix bugs.

To avoid future confusion, I will add a note to the readme and archive the repository.
